project:
  type: book
book:
  title: Foundational Malaria Knowledge
  subtitle: MACEPA Data Fellowship - Training Materials
  chapters:
  - index.qmd
  - part: topic1-intro.qmd
    chapters:
    - topic1a-history-malaria.qmd
    - topic1b-global-impact.qmd
    - topic1c-endemicity.qmd
  - part: topic2-intro.qmd
    chapters: 
    - topic2a-plasmodium-spp.qmd
    - topic2b-lifecycle.qmd
    - topic2c-immunity.qmd 
   - part: topic3-intro.qmd
    chapters: 
    - topic3a-anopheles-trans.qmd
    - topic3b-environment.qmd
    - topic3c-human-behaviour.qmd


bibliography: references.bib
format:
  html:
    theme:
    - cosmo
    - custom.scss
    template-partials: title-block.html
    css: include/webex.css
    include-after-body: include/webex.js
    embed-resources: true 
  pdf:
    documentclass: scrreprt
editor: visual

